name: linux
on: [push]

permissions:
  contents: write

jobs:
  action-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The ${{ github.workspace }} is now ready to test your code on the runner."
      - run: ls ${{ github.workspace }}
      - run: sudo apt update
      - run: sudo apt install zip

      - name: Build
        shell: bash
        run: |
          ./build.sh
          ls ${{ github.workspace }}

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Export package
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          plugin=bilibili-web-fullscreen-extension
          output="$plugin-${{ env.VERSION }}.zip"
          echo "ASSET=$output" >> $GITHUB_ENV

      - name: Upload the package
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.ASSET }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
